### ISSUE TITLE
How to get the trace files?

### ISSUE THREAD

**Issue by yangdongsheng** [djblue/caching#1]
Hi @djblue , 
       It's a great repo about comparing LRU and ARC, thans for your work.
 
There is a question about the tracing result: 
       what's the trace files means? and how did you generate these trace files? I mean, can we say, these trace files can cover most of IO patterns? 

Thanx

**Comment by djblue** [comment]
Hi @yangdongsheng, I'm glad you can take something away from this repo. The trace files were provided as part of an assignment I did over 6 years ago while attending an operating systems class at [ASU](https://www.asu.edu/). I'm not exactly sure how they were generated or how relevant they remain. However, I do think generating a trace file should be a relatively simple and transparent process. Then you would be able to benchmark different algorithms against your specific workload.

**Comment by yangdongsheng** [comment]
Hi @djblue, thanx for your reply!
After some investigation, I think I know where these trace file came from. They were generated first in [1]. The author of this paper:
```
The traces analyzed in this study were collected from both server and PC systems running real user workloads
on three different platforms – Windows NT, IBM AIX and HP-UX. All of them were collected downstream of the database buffer pool and the file system cache, i.e., these are physical address traces, and all hits to the I/O caches in the host system have been removed. The PC traces were collected with VTrace

Most of the traces were gathered over periods of several months but to keep the simulation time manageable, we use only the first 45 days of the traces of which the first 20 days are used to warm up the simulator.
```
They P1 - P14 are collected in PC and there were a FS1(nfs file server), TS1(time server) and DS1(database server). 

After that, when [2] introduce the ARC, it use these trace file for testing. So when somebody want to do ARC testing, they will be used.


[1] W. W. Hsu, A. J. Smith, and H. C. Young,“The automatic im-provement of locality in storage systems.”Tech. Rep., ComputerScience Division, Univ. California, Berkeley, Nov. 2001.
[2]  ARC: A SELF-TUNING, LOW OVERHEAD REPLACEMENT CACHE
